// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protos.proto

package org.ivaxer.cbs.protos;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface HeaderOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required uint64 num_rows = 1;
    boolean hasNumRows();
    long getNumRows();
    
    // optional uint64 block_size = 2;
    boolean hasBlockSize();
    long getBlockSize();
    
    // optional uint64 compressed_block_size = 3;
    boolean hasCompressedBlockSize();
    long getCompressedBlockSize();
    
    // optional uint64 bitmap_size = 4;
    boolean hasBitmapSize();
    long getBitmapSize();
    
    // optional uint64 compressed_bitmap_size = 5;
    boolean hasCompressedBitmapSize();
    long getCompressedBitmapSize();
  }
  public static final class Header extends
      com.google.protobuf.GeneratedMessage
      implements HeaderOrBuilder {
    // Use Header.newBuilder() to construct.
    private Header(Builder builder) {
      super(builder);
    }
    private Header(boolean noInit) {}
    
    private static final Header defaultInstance;
    public static Header getDefaultInstance() {
      return defaultInstance;
    }
    
    public Header getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.ivaxer.cbs.protos.Protos.internal_static_org_ivaxer_cbs_protos_Header_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.ivaxer.cbs.protos.Protos.internal_static_org_ivaxer_cbs_protos_Header_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required uint64 num_rows = 1;
    public static final int NUM_ROWS_FIELD_NUMBER = 1;
    private long numRows_;
    public boolean hasNumRows() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getNumRows() {
      return numRows_;
    }
    
    // optional uint64 block_size = 2;
    public static final int BLOCK_SIZE_FIELD_NUMBER = 2;
    private long blockSize_;
    public boolean hasBlockSize() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getBlockSize() {
      return blockSize_;
    }
    
    // optional uint64 compressed_block_size = 3;
    public static final int COMPRESSED_BLOCK_SIZE_FIELD_NUMBER = 3;
    private long compressedBlockSize_;
    public boolean hasCompressedBlockSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public long getCompressedBlockSize() {
      return compressedBlockSize_;
    }
    
    // optional uint64 bitmap_size = 4;
    public static final int BITMAP_SIZE_FIELD_NUMBER = 4;
    private long bitmapSize_;
    public boolean hasBitmapSize() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public long getBitmapSize() {
      return bitmapSize_;
    }
    
    // optional uint64 compressed_bitmap_size = 5;
    public static final int COMPRESSED_BITMAP_SIZE_FIELD_NUMBER = 5;
    private long compressedBitmapSize_;
    public boolean hasCompressedBitmapSize() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getCompressedBitmapSize() {
      return compressedBitmapSize_;
    }
    
    private void initFields() {
      numRows_ = 0L;
      blockSize_ = 0L;
      compressedBlockSize_ = 0L;
      bitmapSize_ = 0L;
      compressedBitmapSize_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNumRows()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, numRows_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, blockSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, compressedBlockSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, bitmapSize_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, compressedBitmapSize_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, numRows_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, blockSize_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, compressedBlockSize_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, bitmapSize_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, compressedBitmapSize_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.ivaxer.cbs.protos.Protos.Header parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ivaxer.cbs.protos.Protos.Header parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ivaxer.cbs.protos.Protos.Header parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.ivaxer.cbs.protos.Protos.Header parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.ivaxer.cbs.protos.Protos.Header parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ivaxer.cbs.protos.Protos.Header parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.ivaxer.cbs.protos.Protos.Header parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ivaxer.cbs.protos.Protos.Header parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.ivaxer.cbs.protos.Protos.Header parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.ivaxer.cbs.protos.Protos.Header parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.ivaxer.cbs.protos.Protos.Header prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.ivaxer.cbs.protos.Protos.HeaderOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.ivaxer.cbs.protos.Protos.internal_static_org_ivaxer_cbs_protos_Header_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.ivaxer.cbs.protos.Protos.internal_static_org_ivaxer_cbs_protos_Header_fieldAccessorTable;
      }
      
      // Construct using org.ivaxer.cbs.protos.Protos.Header.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        numRows_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        blockSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        compressedBlockSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        bitmapSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        compressedBitmapSize_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.ivaxer.cbs.protos.Protos.Header.getDescriptor();
      }
      
      public org.ivaxer.cbs.protos.Protos.Header getDefaultInstanceForType() {
        return org.ivaxer.cbs.protos.Protos.Header.getDefaultInstance();
      }
      
      public org.ivaxer.cbs.protos.Protos.Header build() {
        org.ivaxer.cbs.protos.Protos.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.ivaxer.cbs.protos.Protos.Header buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.ivaxer.cbs.protos.Protos.Header result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.ivaxer.cbs.protos.Protos.Header buildPartial() {
        org.ivaxer.cbs.protos.Protos.Header result = new org.ivaxer.cbs.protos.Protos.Header(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.numRows_ = numRows_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.blockSize_ = blockSize_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.compressedBlockSize_ = compressedBlockSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.bitmapSize_ = bitmapSize_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.compressedBitmapSize_ = compressedBitmapSize_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.ivaxer.cbs.protos.Protos.Header) {
          return mergeFrom((org.ivaxer.cbs.protos.Protos.Header)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.ivaxer.cbs.protos.Protos.Header other) {
        if (other == org.ivaxer.cbs.protos.Protos.Header.getDefaultInstance()) return this;
        if (other.hasNumRows()) {
          setNumRows(other.getNumRows());
        }
        if (other.hasBlockSize()) {
          setBlockSize(other.getBlockSize());
        }
        if (other.hasCompressedBlockSize()) {
          setCompressedBlockSize(other.getCompressedBlockSize());
        }
        if (other.hasBitmapSize()) {
          setBitmapSize(other.getBitmapSize());
        }
        if (other.hasCompressedBitmapSize()) {
          setCompressedBitmapSize(other.getCompressedBitmapSize());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNumRows()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              numRows_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              blockSize_ = input.readUInt64();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              compressedBlockSize_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              bitmapSize_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              compressedBitmapSize_ = input.readUInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required uint64 num_rows = 1;
      private long numRows_ ;
      public boolean hasNumRows() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getNumRows() {
        return numRows_;
      }
      public Builder setNumRows(long value) {
        bitField0_ |= 0x00000001;
        numRows_ = value;
        onChanged();
        return this;
      }
      public Builder clearNumRows() {
        bitField0_ = (bitField0_ & ~0x00000001);
        numRows_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 block_size = 2;
      private long blockSize_ ;
      public boolean hasBlockSize() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getBlockSize() {
        return blockSize_;
      }
      public Builder setBlockSize(long value) {
        bitField0_ |= 0x00000002;
        blockSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearBlockSize() {
        bitField0_ = (bitField0_ & ~0x00000002);
        blockSize_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 compressed_block_size = 3;
      private long compressedBlockSize_ ;
      public boolean hasCompressedBlockSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public long getCompressedBlockSize() {
        return compressedBlockSize_;
      }
      public Builder setCompressedBlockSize(long value) {
        bitField0_ |= 0x00000004;
        compressedBlockSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearCompressedBlockSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        compressedBlockSize_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 bitmap_size = 4;
      private long bitmapSize_ ;
      public boolean hasBitmapSize() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public long getBitmapSize() {
        return bitmapSize_;
      }
      public Builder setBitmapSize(long value) {
        bitField0_ |= 0x00000008;
        bitmapSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearBitmapSize() {
        bitField0_ = (bitField0_ & ~0x00000008);
        bitmapSize_ = 0L;
        onChanged();
        return this;
      }
      
      // optional uint64 compressed_bitmap_size = 5;
      private long compressedBitmapSize_ ;
      public boolean hasCompressedBitmapSize() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getCompressedBitmapSize() {
        return compressedBitmapSize_;
      }
      public Builder setCompressedBitmapSize(long value) {
        bitField0_ |= 0x00000010;
        compressedBitmapSize_ = value;
        onChanged();
        return this;
      }
      public Builder clearCompressedBitmapSize() {
        bitField0_ = (bitField0_ & ~0x00000010);
        compressedBitmapSize_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.ivaxer.cbs.protos.Header)
    }
    
    static {
      defaultInstance = new Header(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.ivaxer.cbs.protos.Header)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_org_ivaxer_cbs_protos_Header_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_org_ivaxer_cbs_protos_Header_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Protos.proto\022\025org.ivaxer.cbs.protos\"\202\001" +
      "\n\006Header\022\020\n\010num_rows\030\001 \002(\004\022\022\n\nblock_size" +
      "\030\002 \001(\004\022\035\n\025compressed_block_size\030\003 \001(\004\022\023\n" +
      "\013bitmap_size\030\004 \001(\004\022\036\n\026compressed_bitmap_" +
      "size\030\005 \001(\004"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_org_ivaxer_cbs_protos_Header_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_org_ivaxer_cbs_protos_Header_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_org_ivaxer_cbs_protos_Header_descriptor,
              new java.lang.String[] { "NumRows", "BlockSize", "CompressedBlockSize", "BitmapSize", "CompressedBitmapSize", },
              org.ivaxer.cbs.protos.Protos.Header.class,
              org.ivaxer.cbs.protos.Protos.Header.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
